### ISSUE TITLE
Cannot create database outside the docker image with an sqlite3 backend

### ISSUE THREAD

**Issue by mdenker** [G-Node/gindocker#1]
I was trying out the gin docker image as described here:
https://web.gin.g-node.org/G-Node/Info/wiki/In+House

I integrated a folder (/somefolder/) into the image as folder `data` using the -v switch of docker, and in the initial setup of gogs I use sqlite3 set to its default:
`data/gogs.db`

This gives an error
`Connect to database: Fail to create directories: mkdir data: file exists`
Choosing a different directory, e.g., data2, works, but then of course the database lives inside the image. A similar error happens further below with the log file directory, which is also reported as an error to be existent. I'm rather new to docker, am I missing a step here?

**Comment by cgars** [comment]
Hello Michael

thanks for reporting this bug.

The path to the db file needs to be prefixed with a slash:
`/data/gogs.db` 
the same is true for the log file path, which should read: 
`/data/log` 
accordingly

I will fix the defaults in the next gin@home release.

Thanks again!

Christian

**Comment by mdenker** [comment]
Ah, great, thanks Christian, that fixed it!

**Comment by cgars** [comment]
Fixes with new image
