### ISSUE TITLE
Login in to dockerized gin server after creating an account results in extremely slow responding server

### ISSUE THREAD

**Issue by mdenker** [G-Node/gindocker#2]
I installed the gin docker image as described here:
https://web.gin.g-node.org/G-Node/Info/wiki/In+House

During the setup, I select sqlite3 and keep standard settings (except for the fix in #1).

After that page, I am presented with the login page. I choose create account, and enter the required details (user name, password, email, captcha). 

After this, I am taken back to the login page. I here enter user name and password. This results in several minutes of "Waiting for localhost" by the browser (firefox). Eventually, I am logged in, however, also from here on every click results in a long waiting times (minutes) of "Waiting for localhost". The same delay occurs when pushing a repo to the local server using git/gin, i.e.,
`git remote add origin http://localhost:3000/user/Test.git`                                                                                                                
`git push -u origin master`

However, everything seems to work nonetheless -- only slow.  Before account creation, responses were instantaneous.

This behavior is observed independent of whether I mount an external directory as /data into the docker image using the -v switch, or simply keep everything within the container.

Any idea what could be the cause?

**Comment by cgars** [comment]
Hello Micahel

i just fellowed the instruction (well did so a few hours ago see #1 ) and it works fine here!.
Might this be related to #3 ? 

Can you send (garbersatbio.lmu.de) or paste  the content of your docker log file somewhere. You can determine where it is by issuing:

`docker inspect <containername>` 

and searching for the log line.

`docker inspect <containername>| grep log`

containername can be found with 

`docker inspect ps`

Best 

Christian

**Comment by mdenker** [comment]
Hi Christian,

thanks for the help in debugging the setup, I'll send the log file.

I don't think it's related to #3, since it also happens without mounting any external /data...

**Comment by cgars** [comment]
Fixes with new image
