### ISSUE TITLE
Setting the right user for dockerized gin server

### ISSUE THREAD

**Issue by mdenker** [G-Node/gindocker#3]
(This may be an issue either regarding the dockerized code, or requiring more info in the documentation.)

In a nutshell, the problem is that I cannot find a way to set the owner of the data directory outside the docker container (mounted via -v).

I describe the situation in the following.

Assume a Linux system with two users, user Alice at UID 1000 and user Bob at UID 1001.

Bob is in the docker group and can use docker w/o sudo. Bob gets the gindocker image as described here: https://web.gin.g-node.org/G-Node/Info/wiki/In+House

Bob then creates a directory (e.g., /home/bob/gindata) with ownership bob:bob. Running
`docker run -v /home/bob/gindata/:/data -p 3000:3000 -p 2222:22 -d gnode/ginhome`
works, however, the directory is now changed to owner Alice (UID 1000). User Alice is not in the docker group.

Trying to run the image as user Bob explicitely by typing
`docker run -u 1001 -v /home/bob/gindata/:/data -p 3000:3000 -p 2222:22 gnode/ginhome`
fails with a long list of
`chown: changing ownership of '/data/git/somefilename': Operation not permitted`
and finally
`IOError: [Errno 13] Permission denied: '/app/gogs/supervisord.log'`

I am not sure in how far this is an intrinsic issue with docker. However, if there is a good way to specify the user that the dockerized gin server runs under, it would be worthwhile to document this in the quick start cited above, as this could be a very common problem you run into.

**Comment by cgars** [comment]
Hello Michael

It probably important to know that, when specifying the user with -u, the user that runs the server command in the docker container  is (id wise) not necessary the same that runs on the host computer. 

On way to work around this is to fix the uid , but see [here](https://medium.com/@mccode/understanding-how-uid-and-gid-work-in-docker-containers-c37a01d01cf) for an in detail description.

I agree that we should document this and will update the wiki soonish.

Another issue that might arise and/or is important to know, i as the user that issues all the git command, has again another name (and uid - git:1000) [see.](https://github.com/G-Node/gogs/blob/gin%40home/docker/build.sh#L24-L26) 

Thanks for your detailed report btw!

**Comment by cgars** [comment]
To overcome issues with docker -u and user if intransparencies I created the possibility to set the git users (running the gin server in the dockee container) uid (and gid).  
```
docker run -e GITUID="1001" -e GITGID="1001" -it gnode/ginhome
```
